const constants = {
  API_URL: process.env.NEXT_PUBLIC_API_URL || '/api',
  APP_NAME: process.env.NEXT_PUBLIC_APP_NAME || 'ROOSTAY',
  APP_URL: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  APP_DESCRIPTION: 'Find your perfect stay in Ethiopia.',
  DEFAULT_PAGE_SIZE: 12,
  MAX_PAGE_SIZE: 50,
  MAX_IMAGE_SIZE_MB: 5,
  MAX_IMAGES_PER_LISTING: 15,
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
  CURRENCY: 'ETB',
  CURRENCY_SYMBOL: 'Br',
  MIN_NIGHTS_DEFAULT: 1,
  MAX_NIGHTS_DEFAULT: 30,
  CITIES: ['Addis Ababa','Adama','Bahir Dar','Dire Dawa','Gondar','Hawassa','Jimma','Mekelle','Shashamane'],
  PROPERTY_TYPES: [
    { value: 'apartment', label: 'Apartment' },
    { value: 'house', label: 'House' },
    { value: 'villa', label: 'Villa' },
    { value: 'condo', label: 'Condo' },
    { value: 'guest_house', label: 'Guest House' },
    { value: 'shared_room', label: 'Shared Room' },
    { value: 'serviced_apartment', label: 'Serviced Apartment' },
  ],
  LISTING_TYPES: [
    { value: 'short_term', label: 'Short Term' },
    { value: 'long_term', label: 'Long Term' },
    { value: 'both', label: 'Both' },
  ],
  CANCELLATION_POLICIES: [
    { value: 'flexible', label: 'Flexible' },
    { value: 'moderate', label: 'Moderate' },
    { value: 'strict', label: 'Strict' },
  ],
  BOOKING_STATUSES: {
    pending: { label: 'Pending', color: '#F59E0B' },
    confirmed: { label: 'Confirmed', color: '#10B981' },
    cancelled: { label: 'Cancelled', color: '#EF4444' },
    completed: { label: 'Completed', color: '#3B82F6' },
    rejected: { label: 'Rejected', color: '#EF4444' },
    expired: { label: 'Expired', color: '#6B7280' },
  },
  PAYMENT_STATUSES: {
    pending: { label: 'Pending', color: '#F59E0B' },
    processing: { label: 'Processing', color: '#3B82F6' },
    completed: { label: 'Completed', color: '#10B981' },
    failed: { label: 'Failed', color: '#EF4444' },
    refunded: { label: 'Refunded', color: '#8B5CF6' },
    cancelled: { label: 'Cancelled', color: '#6B7280' },
  },
  ROUTES: {
    HOME: '/', LOGIN: '/login', REGISTER: '/register',
    LISTINGS: '/listings', SEARCH: '/search',
    GUEST_DASHBOARD: '/guest/dashboard', GUEST_BOOKINGS: '/guest/bookings',
    GUEST_FAVORITES: '/guest/favorites', GUEST_PROFILE: '/guest/profile',
    HOST_DASHBOARD: '/host/dashboard', HOST_LISTINGS: '/host/listings',
    HOST_LISTINGS_CREATE: '/host/listings/create', HOST_BOOKINGS: '/host/bookings',
    HOST_WITHDRAWALS: '/host/withdrawals',
    ADMIN_DASHBOARD: '/admin/dashboard', ADMIN_USERS: '/admin/users',
    ADMIN_LISTINGS: '/admin/listings', ADMIN_PAYMENTS: '/admin/payments',
    ADMIN_WITHDRAWALS: '/admin/withdrawals', ADMIN_REPORTS: '/admin/reports',
  },
};

export default constants;
